<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'brand'          => 'toyota',
                'model'          => 'Corolla',
                'year'           => 2026,
                'version'        => 'Corolla elite 1.8 AT china',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'China',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/corolla/corolla-elite-1-8-at-china/IMG_6407.jpg', 'vehicles/toyota/corolla/corolla-elite-1-8-at-china/IMG_6408.jpg', 'vehicles/toyota/corolla/corolla-elite-1-8-at-china/IMG_6409.jpg', 'vehicles/toyota/corolla/corolla-elite-1-8-at-china/IMG_6410.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Corolla',
                'year'           => 2026,
                'version'        => 'Corolla GLi 1.6L AT GCC',
                'engine'         => '1.6L',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/corolla/corolla-gli-1-6l-at-gcc/IMG_6395.jpg', 'vehicles/toyota/corolla/corolla-gli-1-6l-at-gcc/IMG_6396.jpg', 'vehicles/toyota/corolla/corolla-gli-1-6l-at-gcc/IMG_6397.jpg', 'vehicles/toyota/corolla/corolla-gli-1-6l-at-gcc/IMG_6398.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Corolla',
                'year'           => 2026,
                'version'        => 'Corolla GR Sport 1.6L Turbo MT GCC',
                'engine'         => '1.6L Turbo',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/corolla/corolla-gr-sport-1-6l-turbo-mt-gcc/IMG_6403.jpg', 'vehicles/toyota/corolla/corolla-gr-sport-1-6l-turbo-mt-gcc/IMG_6404.jpg', 'vehicles/toyota/corolla/corolla-gr-sport-1-6l-turbo-mt-gcc/IMG_6405.jpg', 'vehicles/toyota/corolla/corolla-gr-sport-1-6l-turbo-mt-gcc/IMG_6406.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Corolla',
                'year'           => 2026,
                'version'        => 'Corolla XLi 1.6L AT GCC',
                'engine'         => '1.6L',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/corolla/corolla-xli-1-6l-at-gcc/IMG_6391.jpg', 'vehicles/toyota/corolla/corolla-xli-1-6l-at-gcc/IMG_6392.jpg', 'vehicles/toyota/corolla/corolla-xli-1-6l-at-gcc/IMG_6393.jpg', 'vehicles/toyota/corolla/corolla-xli-1-6l-at-gcc/IMG_6394.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Corolla',
                'year'           => 2026,
                'version'        => 'Corolla XLi 2.0L AT GCC',
                'engine'         => '2.0L',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/corolla/corolla-xli-2-0l-at-gcc/IMG_6399.jpg', 'vehicles/toyota/corolla/corolla-xli-2-0l-at-gcc/IMG_6400.jpg', 'vehicles/toyota/corolla/corolla-xli-2-0l-at-gcc/IMG_6401.jpg', 'vehicles/toyota/corolla/corolla-xli-2-0l-at-gcc/IMG_6402.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Corolla Cross',
                'year'           => 2026,
                'version'        => 'Corolla cross 1.8 hybrid Gcc',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/corolla-cross/corolla-cross-1-8-hybrid-gcc/IMG_6426.jpg', 'vehicles/toyota/corolla-cross/corolla-cross-1-8-hybrid-gcc/IMG_6427.jpg', 'vehicles/toyota/corolla-cross/corolla-cross-1-8-hybrid-gcc/IMG_6428.jpg', 'vehicles/toyota/corolla-cross/corolla-cross-1-8-hybrid-gcc/IMG_6429.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Corolla Cross',
                'year'           => 2026,
                'version'        => 'Corolla cross elite hybrid',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/corolla-cross/corolla-cross-elite-hybrid/IMG_6430.jpg', 'vehicles/toyota/corolla-cross/corolla-cross-elite-hybrid/IMG_6431.jpg', 'vehicles/toyota/corolla-cross/corolla-cross-elite-hybrid/IMG_6432.jpg', 'vehicles/toyota/corolla-cross/corolla-cross-elite-hybrid/IMG_6433.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Fortuner',
                'year'           => 2026,
                'version'        => 'Fortuner Dubai 2.7 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/fortuner/fortuner-dubai-2-7-gasoline-4x4-gcc/IMG_1127.jpg', 'vehicles/toyota/fortuner/fortuner-dubai-2-7-gasoline-4x4-gcc/IMG_1128.jpg', 'vehicles/toyota/fortuner/fortuner-dubai-2-7-gasoline-4x4-gcc/IMG_1129.jpg', 'vehicles/toyota/fortuner/fortuner-dubai-2-7-gasoline-4x4-gcc/IMG_1130.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Fortuner',
                'year'           => 2026,
                'version'        => 'Fortuner EX 2.7 Gasoline 4x2 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x2-gcc/IMG_1123.jpg', 'vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x2-gcc/IMG_1124.jpg', 'vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x2-gcc/IMG_1125.jpg', 'vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x2-gcc/IMG_1126.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Fortuner',
                'year'           => 2026,
                'version'        => 'Fortuner EX 2.7 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x4-gcc/IMG_6957.PNG', 'vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x4-gcc/IMG_6958.PNG', 'vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x4-gcc/IMG_6959.PNG', 'vehicles/toyota/fortuner/fortuner-ex-2-7-gasoline-4x4-gcc/IMG_6960.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Fortuner',
                'year'           => 2026,
                'version'        => 'Fortuner VX 4.0 V6 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/fortuner/fortuner-vx-4-0-v6-gasoline-4x4-gcc/IMG_6961.PNG', 'vehicles/toyota/fortuner/fortuner-vx-4-0-v6-gasoline-4x4-gcc/IMG_6962.PNG', 'vehicles/toyota/fortuner/fortuner-vx-4-0-v6-gasoline-4x4-gcc/IMG_6963.PNG', 'vehicles/toyota/fortuner/fortuner-vx-4-0-v6-gasoline-4x4-gcc/IMG_6964.PNG', 'vehicles/toyota/fortuner/fortuner-vx-4-0-v6-gasoline-4x4-gcc/IMG_6965.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Highlander',
                'year'           => 2026,
                'version'        => 'Highlander LE 2.5 HybridGCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/highlander/highlander-le-2-5-hybridgcc/IMG_6470.jpg', 'vehicles/toyota/highlander/highlander-le-2-5-hybridgcc/IMG_6471.jpg', 'vehicles/toyota/highlander/highlander-le-2-5-hybridgcc/IMG_6472.jpg', 'vehicles/toyota/highlander/highlander-le-2-5-hybridgcc/IMG_6473.jpg', 'vehicles/toyota/highlander/highlander-le-2-5-hybridgcc/IMG_6474.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Highlander',
                'year'           => 2026,
                'version'        => 'Highlander Limited 2.5 Hybrid GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc-2/IMG_6487.jpg', 'vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc-2/IMG_6488.jpg', 'vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc-2/IMG_6489.jpg', 'vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc-2/IMG_6490.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Highlander',
                'year'           => 2026,
                'version'        => 'Highlander Limited 2.5 hybrid GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc/IMG_6481.jpg', 'vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc/IMG_6482.jpg', 'vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc/IMG_6484.jpg', 'vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc/IMG_6485.jpg', 'vehicles/toyota/highlander/highlander-limited-2-5-hybrid-gcc/IMG_6486.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux Adventure 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-adventure-4-0-v6-gasoline-at-4x4-gcc/IMG_6926.PNG', 'vehicles/toyota/hilux/hilux-adventure-4-0-v6-gasoline-at-4x4-gcc/IMG_6927.PNG', 'vehicles/toyota/hilux/hilux-adventure-4-0-v6-gasoline-at-4x4-gcc/IMG_6928.PNG', 'vehicles/toyota/hilux/hilux-adventure-4-0-v6-gasoline-at-4x4-gcc/IMG_6929.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux champion 2.4 diesel 4x2 AT',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-champion-2-4-diesel-4x2-at/IMG_6491.jpg', 'vehicles/toyota/hilux/hilux-champion-2-4-diesel-4x2-at/IMG_6492.jpg', 'vehicles/toyota/hilux/hilux-champion-2-4-diesel-4x2-at/IMG_6493.jpg', 'vehicles/toyota/hilux/hilux-champion-2-4-diesel-4x2-at/IMG_6494.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2027,
                'version'        => 'Hilux Conquest 2.8L Diesel AT 4x4 2027',
                'engine'         => '2.8L Diesel',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-conquest-2-8l-diesel-at-4x4-2027/7fb99f20-d626-4977-ab59-14aa05f0845e.jpg', 'vehicles/toyota/hilux/hilux-conquest-2-8l-diesel-at-4x4-2027/9ab7d0cb-a1ae-452b-8a6b-ba8b6eda03ac.jpg', 'vehicles/toyota/hilux/hilux-conquest-2-8l-diesel-at-4x4-2027/f69346ea-7f71-4818-bf47-8ba78d161f68.jpg', 'vehicles/toyota/hilux/hilux-conquest-2-8l-diesel-at-4x4-2027/fce4350d-18a6-4dec-acc8-4e1193e2ef1d.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux DLX 2.4D MT 4x2 GCC',
                'engine'         => '2.4D Diesel',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x2-gcc/IMG_6890.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x2-gcc/IMG_6891.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x2-gcc/IMG_6892.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x2-gcc/IMG_6893.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux DLX 2.4D MT 4x4 GCC',
                'engine'         => '2.4D Diesel',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x4-gcc/IMG_6895.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x4-gcc/IMG_6896.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x4-gcc/IMG_6897.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-4d-mt-4x4-gcc/IMG_6898.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux DLX 2.7 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-at-4x4-gcc/IMG_6940.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-at-4x4-gcc/IMG_6941.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-at-4x4-gcc/IMG_6942.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-at-4x4-gcc/IMG_6943.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux DLX 2.7 Gasoline MT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-mt-4x4-gcc/IMG_6935.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-mt-4x4-gcc/IMG_6936.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-mt-4x4-gcc/IMG_6937.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-gasoline-mt-4x4-gcc/IMG_6938.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux DLX 2.7 MT 4x2 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x2-gcc/IMG_6884.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x2-gcc/IMG_6885.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x2-gcc/IMG_6886.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x2-gcc/IMG_6887.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux DLX 2.7 MT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x4-gcc/IMG_6880.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x4-gcc/IMG_6881.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x4-gcc/IMG_6882.PNG', 'vehicles/toyota/hilux/hilux-dlx-2-7-mt-4x4-gcc/IMG_6883.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux E 2.8L Diesel MT 4x4 2027',
                'engine'         => '2.8L Diesel',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-e-2-8l-diesel-mt-4x4-2027/IMG_6918.PNG', 'vehicles/toyota/hilux/hilux-e-2-8l-diesel-mt-4x4-2027/IMG_6919.PNG', 'vehicles/toyota/hilux/hilux-e-2-8l-diesel-mt-4x4-2027/IMG_6920.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux GLXS-SR5 2.7 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-at-4x4-gcc/51c402d1-cd9a-49d5-9bed-6334f00ba30b.jpg', 'vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-at-4x4-gcc/9b961eac-f019-4436-a83e-7a6341226740.jpg', 'vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-at-4x4-gcc/a379d569-db2d-4a78-be6e-aaa7a13c377e.jpg', 'vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-at-4x4-gcc/e4a39a00-4360-487f-8fa9-30e093f290f5.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux GLXS-SR5 2.7 Gasoline MT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-mt-4x4-gcc/IMG_6914.PNG', 'vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-mt-4x4-gcc/IMG_6915.PNG', 'vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-mt-4x4-gcc/IMG_6916.PNG', 'vehicles/toyota/hilux/hilux-glxs-sr5-2-7-gasoline-mt-4x4-gcc/IMG_6917.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux GR Sport 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-gr-sport-4-0-v6-gasoline-at-4x4-gcc/IMG_6922.PNG', 'vehicles/toyota/hilux/hilux-gr-sport-4-0-v6-gasoline-at-4x4-gcc/IMG_6923.PNG', 'vehicles/toyota/hilux/hilux-gr-sport-4-0-v6-gasoline-at-4x4-gcc/IMG_6924.PNG', 'vehicles/toyota/hilux/hilux-gr-sport-4-0-v6-gasoline-at-4x4-gcc/IMG_6925.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Hilux',
                'year'           => 2026,
                'version'        => 'Hilux SR5 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/hilux/hilux-sr5-4-0-v6-gasoline-at-4x4-gcc/IMG_6930.PNG', 'vehicles/toyota/hilux/hilux-sr5-4-0-v6-gasoline-at-4x4-gcc/IMG_6931.PNG', 'vehicles/toyota/hilux/hilux-sr5-4-0-v6-gasoline-at-4x4-gcc/IMG_6932.PNG', 'vehicles/toyota/hilux/hilux-sr5-4-0-v6-gasoline-at-4x4-gcc/IMG_6933.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 EXR 4.0 V6 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-exr-4-0-v6-gasoline-4x4-gcc/IMG_6318.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-exr-4-0-v6-gasoline-4x4-gcc/IMG_6319.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-exr-4-0-v6-gasoline-4x4-gcc/IMG_6320.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GR Sport 3.5 Twin Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7095.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7096.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7097.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7098.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GR Sport 3.5 Twin Turbo Hybrid 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7139.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7140.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7141.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gr-sport-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7142.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR Base 3.5 Twin Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-base-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7123.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-base-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7124.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-base-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7125.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-base-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7126.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR High 3.5 Twin Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7109.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7110.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7111.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7112.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR High 4.0 V6 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-4-0-v6-gasoline-4x4-gcc/IMG_7090.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-4-0-v6-gasoline-4x4-gcc/IMG_7091.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-4-0-v6-gasoline-4x4-gcc/IMG_7092.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-4-0-v6-gasoline-4x4-gcc/IMG_7093.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR High Option 3.5 Twin Turbo Hybrid 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7127.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7128.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7129.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-high-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7130.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR Low 3.5 Twin Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7119.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7120.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7121.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7122.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR Low 4.0 V6 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-4-0-v6-gasoline-4x4-gcc/IMG_7069.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-4-0-v6-gasoline-4x4-gcc/IMG_7070.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-4-0-v6-gasoline-4x4-gcc/IMG_7071.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-4-0-v6-gasoline-4x4-gcc/IMG_7072.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR Low Option 3.5 Twin Turbo Hybrid 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7131.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7132.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7133.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-low-option-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7134.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR Medium 3.5 Twin Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7115.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7116.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7117.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7118.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 GXR Medium 4.0 V6 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-4-0-v6-gasoline-4x4-gcc/IMG_7077.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-4-0-v6-gasoline-4x4-gcc/IMG_7078.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-4-0-v6-gasoline-4x4-gcc/IMG_7079.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-gxr-medium-4-0-v6-gasoline-4x4-gcc/IMG_7080.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 VX 3.5 Twin Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7104.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7105.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7106.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7107.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 VX 4.0 V6 Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-4-0-v6-gasoline-4x4-gcc/IMG_6327.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-4-0-v6-gasoline-4x4-gcc/IMG_6328.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-4-0-v6-gasoline-4x4-gcc/IMG_6329.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-4-0-v6-gasoline-4x4-gcc/IMG_6330.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vx-4-0-v6-gasoline-4x4-gcc/IMG_6331.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 VXR 3.5 Twin Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7100.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7101.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7102.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-gasoline-4x4-gcc/IMG_7103.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 300',
                'year'           => 2026,
                'version'        => 'Land Cruiser 300 VXR 3.5 Twin Turbo Hybrid 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7135.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7136.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7137.PNG', 'vehicles/toyota/land-cruiser-300/land-cruiser-300-vxr-3-5-twin-turbo-hybrid-4x4-gcc/IMG_7138.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC71 2-Door Hardtop Base 4.0 V6 Gasoline MT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6994.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6995.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6996.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6997.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC71 2-Door Hardtop LX 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_6983.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_6984.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_6985.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC71 2-Door Hardtop LX Full 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6990.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6991.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6992.PNG', 'vehicles/toyota/land-cruiser-70/lc71-2-door-hardtop-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6993.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC76 4-Door Hardtop Wagon Base 4.0 V6 Gasoline MT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7052.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7053.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7054.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7055.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC76 4-Door Hardtop Wagon LX 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7041.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7042.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7043.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7044.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC76 4-Door Hardtop Wagon LX Full 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7047.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7048.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7050.PNG', 'vehicles/toyota/land-cruiser-70/lc76-4-door-hardtop-wagon-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7051.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC78 2-Door Troop Carrier 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0-v6-gasoline-at-4x4-gcc/IMG_6986.PNG', 'vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0-v6-gasoline-at-4x4-gcc/IMG_6987.PNG', 'vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0-v6-gasoline-at-4x4-gcc/IMG_6988.PNG', 'vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0-v6-gasoline-at-4x4-gcc/IMG_6989.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC78 2-Door Troop Carrier 4.0L V6 gasoline MT 4x4 GCC',
                'engine'         => '4.0L V6 gasoline',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0l-v6-gasoline-mt-4x4-gcc/IMG_6978.PNG', 'vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0l-v6-gasoline-mt-4x4-gcc/IMG_6979.PNG', 'vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0l-v6-gasoline-mt-4x4-gcc/IMG_6980.PNG', 'vehicles/toyota/land-cruiser-70/lc78-2-door-troop-carrier-4-0l-v6-gasoline-mt-4x4-gcc/IMG_6981.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC79 2-Door Pickup LX 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_6970.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_6971.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_6972.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC79 2-Door Pickup LX Base 4.0 V6 Gasoline MT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6966.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6967.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6968.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_6969.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC79 2-Door Pickup LX Full 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6973.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6974.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6975.PNG', 'vehicles/toyota/land-cruiser-70/lc79-2-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_6977.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC79 4-Door Pickup Base 4.0 V6 Gasoline MT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7030.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7031.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7032.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-base-4-0-v6-gasoline-mt-4x4-gcc/IMG_7033.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC79 4-Door Pickup LX 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7021.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7022.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7023.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-4-0-v6-gasoline-at-4x4-gcc/IMG_7024.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Land Cruiser 70',
                'year'           => 2026,
                'version'        => 'LC79 4-Door Pickup LX Full 4.0 V6 Gasoline AT 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7026.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7027.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7028.PNG', 'vehicles/toyota/land-cruiser-70/lc79-4-door-pickup-lx-full-4-0-v6-gasoline-at-4x4-gcc/IMG_7029.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Prado',
                'year'           => 2026,
                'version'        => 'Prado Adventure 2.4 Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/prado/prado-adventure-2-4-turbo-gasoline-4x4-gcc/1ff2d831-aa2e-4429-8176-701d87f374e9.jpg', 'vehicles/toyota/prado/prado-adventure-2-4-turbo-gasoline-4x4-gcc/2780a4b9-8815-42af-ab8b-40c30f5243ab.jpg', 'vehicles/toyota/prado/prado-adventure-2-4-turbo-gasoline-4x4-gcc/32741efd-25b2-45d6-87f8-353368f4e2ae.jpg', 'vehicles/toyota/prado/prado-adventure-2-4-turbo-gasoline-4x4-gcc/74334113-bff2-4ccd-9abd-7c67909fc71a.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Prado',
                'year'           => 2026,
                'version'        => 'Prado First Edition 2.4 Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/prado/prado-first-edition-2-4-turbo-gasoline-4x4-gcc/IMG_7060.PNG', 'vehicles/toyota/prado/prado-first-edition-2-4-turbo-gasoline-4x4-gcc/IMG_7061.PNG', 'vehicles/toyota/prado/prado-first-edition-2-4-turbo-gasoline-4x4-gcc/IMG_7062.PNG', 'vehicles/toyota/prado/prado-first-edition-2-4-turbo-gasoline-4x4-gcc/IMG_7063.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Prado',
                'year'           => 2026,
                'version'        => 'Prado TXL 2.4 Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/prado/prado-txl-2-4-turbo-gasoline-4x4-gcc/IMG_7056.PNG', 'vehicles/toyota/prado/prado-txl-2-4-turbo-gasoline-4x4-gcc/IMG_7057.PNG', 'vehicles/toyota/prado/prado-txl-2-4-turbo-gasoline-4x4-gcc/IMG_7058.PNG', 'vehicles/toyota/prado/prado-txl-2-4-turbo-gasoline-4x4-gcc/IMG_7059.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Prado',
                'year'           => 2026,
                'version'        => 'Prado VXR 2.4 Turbo Gasoline 4x4 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/prado/prado-vxr-2-4-turbo-gasoline-4x4-gcc/IMG_7064.PNG', 'vehicles/toyota/prado/prado-vxr-2-4-turbo-gasoline-4x4-gcc/IMG_7065.PNG', 'vehicles/toyota/prado/prado-vxr-2-4-turbo-gasoline-4x4-gcc/IMG_7067.PNG', 'vehicles/toyota/prado/prado-vxr-2-4-turbo-gasoline-4x4-gcc/IMG_7068.PNG'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'adventure 2.5 hybrid Gcc',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/adventure-2-5-hybrid-gcc/IMG_6444.jpg', 'vehicles/toyota/rav4/adventure-2-5-hybrid-gcc/IMG_6445.jpg', 'vehicles/toyota/rav4/adventure-2-5-hybrid-gcc/IMG_6446.jpg', 'vehicles/toyota/rav4/adventure-2-5-hybrid-gcc/IMG_6447.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'LE 2.0 GCC',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/le-2-0-gcc/IMG_6439.jpg', 'vehicles/toyota/rav4/le-2-0-gcc/IMG_6440.jpg', 'vehicles/toyota/rav4/le-2-0-gcc/IMG_6441.jpg', 'vehicles/toyota/rav4/le-2-0-gcc/IMG_6442.jpg', 'vehicles/toyota/rav4/le-2-0-gcc/IMG_6443.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'Limited 2.5 hybrid Gcc',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/limited-2-5-hybrid-gcc/IMG_6453.jpg', 'vehicles/toyota/rav4/limited-2-5-hybrid-gcc/IMG_6454.jpg', 'vehicles/toyota/rav4/limited-2-5-hybrid-gcc/IMG_6455.jpg', 'vehicles/toyota/rav4/limited-2-5-hybrid-gcc/IMG_6456.jpg', 'vehicles/toyota/rav4/limited-2-5-hybrid-gcc/IMG_6457.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'RAV4 luxury 2.0L Petrol China',
                'engine'         => '2.0L Petrol',
                'transmission'   => 'Automática',
                'origin_country' => 'China',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/rav4-luxury-2-0l-petrol-china/IMG_6463.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-0l-petrol-china/IMG_6464.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-0l-petrol-china/IMG_6465.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-0l-petrol-china/IMG_6466.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-0l-petrol-china/IMG_6467.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-0l-petrol-china/IMG_6468.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'RAV4 Luxury 2.5 hybrid China',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'China',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/rav4-luxury-2-5-hybrid-china/IMG_6463.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-5-hybrid-china/IMG_6464.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-5-hybrid-china/IMG_6465.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-5-hybrid-china/IMG_6466.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-5-hybrid-china/IMG_6467.jpg', 'vehicles/toyota/rav4/rav4-luxury-2-5-hybrid-china/IMG_6468.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'vxr 2.5 hybrid Gcc',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/vxr-2-5-hybrid-gcc/IMG_6458.jpg', 'vehicles/toyota/rav4/vxr-2-5-hybrid-gcc/IMG_6459.jpg', 'vehicles/toyota/rav4/vxr-2-5-hybrid-gcc/IMG_6460.jpg', 'vehicles/toyota/rav4/vxr-2-5-hybrid-gcc/IMG_6461.jpg', 'vehicles/toyota/rav4/vxr-2-5-hybrid-gcc/IMG_6462.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'XLE 2.0 Gcc',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/xle-2-0-gcc/IMG_6434.jpg', 'vehicles/toyota/rav4/xle-2-0-gcc/IMG_6435.jpg', 'vehicles/toyota/rav4/xle-2-0-gcc/IMG_6436.jpg', 'vehicles/toyota/rav4/xle-2-0-gcc/IMG_6437.jpg', 'vehicles/toyota/rav4/xle-2-0-gcc/IMG_6438.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Rav4',
                'year'           => 2026,
                'version'        => 'XSE 2.5 hybrid Gcc',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/rav4/xse-2-5-hybrid-gcc/IMG_6448.jpg', 'vehicles/toyota/rav4/xse-2-5-hybrid-gcc/IMG_6449.jpg', 'vehicles/toyota/rav4/xse-2-5-hybrid-gcc/IMG_6450.jpg', 'vehicles/toyota/rav4/xse-2-5-hybrid-gcc/IMG_6451.jpg', 'vehicles/toyota/rav4/xse-2-5-hybrid-gcc/IMG_6452.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Yaris',
                'year'           => 2026,
                'version'        => 'Yaris E 1.2 CVT GCC',
                'engine'         => null,
                'transmission'   => 'CVT',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/yaris/yaris-e-1-2-cvt-gcc/IMG_6411.jpg', 'vehicles/toyota/yaris/yaris-e-1-2-cvt-gcc/IMG_6412.jpg', 'vehicles/toyota/yaris/yaris-e-1-2-cvt-gcc/IMG_6414.jpg', 'vehicles/toyota/yaris/yaris-e-1-2-cvt-gcc/IMG_6415.jpg'],
            ],
            [
                'brand'          => 'toyota',
                'model'          => 'Yaris',
                'year'           => 2026,
                'version'        => 'Yaris GR 1.6 turbo MT GCC',
                'engine'         => null,
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/toyota/yaris/yaris-gr-1-6-turbo-mt-gcc/IMG_6416.jpg', 'vehicles/toyota/yaris/yaris-gr-1-6-turbo-mt-gcc/IMG_6417.jpg', 'vehicles/toyota/yaris/yaris-gr-1-6-turbo-mt-gcc/IMG_6418.jpg'],
            ],
            [
                'brand'          => 'mitsubishi',
                'model'          => 'L200',
                'year'           => 2027,
                'version'        => 'L200 GL 2.4L gasolina 4x4 MT',
                'engine'         => '2.4L gasolina',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/mitsubishi/l200/l200-gl-2-4l-gasolina-4x4-mt/IMG_5330.PNG', 'vehicles/mitsubishi/l200/l200-gl-2-4l-gasolina-4x4-mt/IMG_5331.PNG', 'vehicles/mitsubishi/l200/l200-gl-2-4l-gasolina-4x4-mt/IMG_5334.PNG', 'vehicles/mitsubishi/l200/l200-gl-2-4l-gasolina-4x4-mt/IMG_5335.PNG'],
            ],
            [
                'brand'          => 'mitsubishi',
                'model'          => 'L200',
                'year'           => 2027,
                'version'        => 'L200 GLS 2.4L gasolina 4x4 MT',
                'engine'         => '2.4L gasolina',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/mitsubishi/l200/l200-gls-2-4l-gasolina-4x4-mt/IMG_7143.JPG', 'vehicles/mitsubishi/l200/l200-gls-2-4l-gasolina-4x4-mt/IMG_7144.JPG', 'vehicles/mitsubishi/l200/l200-gls-2-4l-gasolina-4x4-mt/IMG_7145.JPG', 'vehicles/mitsubishi/l200/l200-gls-2-4l-gasolina-4x4-mt/IMG_7146.JPG'],
            ],
            [
                'brand'          => 'mitsubishi',
                'model'          => 'Montero Sport',
                'year'           => 2026,
                'version'        => 'Montero sport Full option 3.0L Gasolina 4x4',
                'engine'         => '3.0L Gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/mitsubishi/montero-sport/montero-sport-full-option-3-0l-gasolina-4x4/IMG_7152.PNG', 'vehicles/mitsubishi/montero-sport/montero-sport-full-option-3-0l-gasolina-4x4/IMG_7153.PNG', 'vehicles/mitsubishi/montero-sport/montero-sport-full-option-3-0l-gasolina-4x4/IMG_7154.PNG', 'vehicles/mitsubishi/montero-sport/montero-sport-full-option-3-0l-gasolina-4x4/IMG_7155.PNG'],
            ],
            [
                'brand'          => 'mitsubishi',
                'model'          => 'Montero Sport',
                'year'           => 2026,
                'version'        => 'Montero sport Full option Sportivo 3.0L Gasolina 4x4',
                'engine'         => '3.0L Gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/mitsubishi/montero-sport/montero-sport-full-option-sportivo-3-0l-gasolina-4x4/IMG_7156.PNG', 'vehicles/mitsubishi/montero-sport/montero-sport-full-option-sportivo-3-0l-gasolina-4x4/IMG_7157.PNG', 'vehicles/mitsubishi/montero-sport/montero-sport-full-option-sportivo-3-0l-gasolina-4x4/IMG_7159.PNG', 'vehicles/mitsubishi/montero-sport/montero-sport-full-option-sportivo-3-0l-gasolina-4x4/IMG_7160.PNG'],
            ],
            [
                'brand'          => 'mitsubishi',
                'model'          => 'Outlander',
                'year'           => 2026,
                'version'        => 'Outlander high line 2.5L gasolina 4x4',
                'engine'         => '2.5L gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/mitsubishi/outlander/outlander-high-line-2-5l-gasolina-4x4/IMG_7147.PNG', 'vehicles/mitsubishi/outlander/outlander-high-line-2-5l-gasolina-4x4/IMG_7148.PNG', 'vehicles/mitsubishi/outlander/outlander-high-line-2-5l-gasolina-4x4/IMG_7150.PNG', 'vehicles/mitsubishi/outlander/outlander-high-line-2-5l-gasolina-4x4/IMG_7151.PNG'],
            ],
            [
                'brand'          => 'mitsubishi',
                'model'          => 'Xforce',
                'year'           => 2026,
                'version'        => 'Xforce P-Line 1.5L gasolina',
                'engine'         => '1.5L gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/mitsubishi/xforce/xforce-p-line-1-5l-gasolina/IMG_7165.PNG', 'vehicles/mitsubishi/xforce/xforce-p-line-1-5l-gasolina/IMG_7166.PNG', 'vehicles/mitsubishi/xforce/xforce-p-line-1-5l-gasolina/IMG_7167.PNG', 'vehicles/mitsubishi/xforce/xforce-p-line-1-5l-gasolina/IMG_7168.PNG'],
            ],
            [
                'brand'          => 'mitsubishi',
                'model'          => 'Xpander',
                'year'           => 2026,
                'version'        => 'Xpander cross 1.5L gasolina',
                'engine'         => '1.5L gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/mitsubishi/xpander/xpander-cross-1-5l-gasolina/IMG_7161.PNG', 'vehicles/mitsubishi/xpander/xpander-cross-1-5l-gasolina/IMG_7162.PNG', 'vehicles/mitsubishi/xpander/xpander-cross-1-5l-gasolina/IMG_7163.PNG', 'vehicles/mitsubishi/xpander/xpander-cross-1-5l-gasolina/IMG_7164.PNG'],
            ],
            [
                'brand'          => 'suzuki',
                'model'          => 'Baleno',
                'year'           => 2026,
                'version'        => 'Baleno GL 1.4L gasolina',
                'engine'         => '1.4L gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/suzuki/baleno/baleno-gl-1-4l-gasolina/IMG_7169.PNG', 'vehicles/suzuki/baleno/baleno-gl-1-4l-gasolina/IMG_7170.PNG', 'vehicles/suzuki/baleno/baleno-gl-1-4l-gasolina/IMG_7171.PNG', 'vehicles/suzuki/baleno/baleno-gl-1-4l-gasolina/IMG_7172.PNG'],
            ],
            [
                'brand'          => 'suzuki',
                'model'          => 'Baleno',
                'year'           => 2026,
                'version'        => 'Baleno GLX 1.4L gasolina',
                'engine'         => '1.4L gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/suzuki/baleno/baleno-glx-1-4l-gasolina/IMG_7173.PNG', 'vehicles/suzuki/baleno/baleno-glx-1-4l-gasolina/IMG_7175.PNG', 'vehicles/suzuki/baleno/baleno-glx-1-4l-gasolina/IMG_7176.PNG', 'vehicles/suzuki/baleno/baleno-glx-1-4l-gasolina/IMG_7177.PNG'],
            ],
            [
                'brand'          => 'suzuki',
                'model'          => 'Fronx',
                'year'           => 2026,
                'version'        => 'Fronx GLX 1.5L hybrid gasolina',
                'engine'         => '1.5L hybrid gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/suzuki/fronx/fronx-glx-1-5l-hybrid-gasolina/IMG_7192.PNG', 'vehicles/suzuki/fronx/fronx-glx-1-5l-hybrid-gasolina/IMG_7193.PNG', 'vehicles/suzuki/fronx/fronx-glx-1-5l-hybrid-gasolina/IMG_7194.PNG', 'vehicles/suzuki/fronx/fronx-glx-1-5l-hybrid-gasolina/IMG_7195.PNG'],
            ],
            [
                'brand'          => 'suzuki',
                'model'          => 'Jimny',
                'year'           => 2026,
                'version'        => 'Jimmy GLX 2 door AT',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/suzuki/jimny/jimmy-glx-2-door-at/IMG_7188.PNG', 'vehicles/suzuki/jimny/jimmy-glx-2-door-at/IMG_7189.PNG', 'vehicles/suzuki/jimny/jimmy-glx-2-door-at/IMG_7190.PNG', 'vehicles/suzuki/jimny/jimmy-glx-2-door-at/IMG_7191.PNG'],
            ],
            [
                'brand'          => 'suzuki',
                'model'          => 'Jimny',
                'year'           => 2026,
                'version'        => 'Jimny GLX 4 door AT',
                'engine'         => null,
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/suzuki/jimny/jimny-glx-4-door-at/IMG_7184.PNG', 'vehicles/suzuki/jimny/jimny-glx-4-door-at/IMG_7185.PNG', 'vehicles/suzuki/jimny/jimny-glx-4-door-at/IMG_7186.PNG', 'vehicles/suzuki/jimny/jimny-glx-4-door-at/IMG_7187.PNG'],
            ],
            [
                'brand'          => 'suzuki',
                'model'          => 'Swift',
                'year'           => 2027,
                'version'        => 'Swift GLX 1.2L gasolina',
                'engine'         => '1.2L gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/suzuki/swift/swift-glx-1-2l-gasolina/IMG_6269.jpg', 'vehicles/suzuki/swift/swift-glx-1-2l-gasolina/IMG_7180.PNG', 'vehicles/suzuki/swift/swift-glx-1-2l-gasolina/IMG_7181.PNG', 'vehicles/suzuki/swift/swift-glx-1-2l-gasolina/IMG_7182.PNG', 'vehicles/suzuki/swift/swift-glx-1-2l-gasolina/IMG_7183.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'GX',
                'year'           => 2026,
                'version'        => 'GX 550 3.5L twinturbo gasolina',
                'engine'         => '3.5L Twin Turbo gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/gx/gx-550-3-5l-twinturbo-gasolina/IMG_7197.PNG', 'vehicles/lexus/gx/gx-550-3-5l-twinturbo-gasolina/IMG_7199.PNG', 'vehicles/lexus/gx/gx-550-3-5l-twinturbo-gasolina/IMG_7200.PNG', 'vehicles/lexus/gx/gx-550-3-5l-twinturbo-gasolina/IMG_7201.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LBX',
                'year'           => 2026,
                'version'        => 'LBX 1.5L hybrid gasolina',
                'engine'         => '1.5L hybrid gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lbx/lbx-1-5l-hybrid-gasolina/IMG_7202.PNG', 'vehicles/lexus/lbx/lbx-1-5l-hybrid-gasolina/IMG_7203.PNG', 'vehicles/lexus/lbx/lbx-1-5l-hybrid-gasolina/IMG_7204.PNG', 'vehicles/lexus/lbx/lbx-1-5l-hybrid-gasolina/IMG_7205.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LX',
                'year'           => 2026,
                'version'        => 'Lexus LX 600 F Sport 3.5L twinturbo gasolina',
                'engine'         => '3.5L Twin Turbo gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lx/lexus-lx-600-f-sport-3-5l-twinturbo-gasolina/IMG_7219.PNG', 'vehicles/lexus/lx/lexus-lx-600-f-sport-3-5l-twinturbo-gasolina/IMG_7220.PNG', 'vehicles/lexus/lx/lexus-lx-600-f-sport-3-5l-twinturbo-gasolina/IMG_7221.PNG', 'vehicles/lexus/lx/lexus-lx-600-f-sport-3-5l-twinturbo-gasolina/IMG_7222.PNG', 'vehicles/lexus/lx/lexus-lx-600-f-sport-3-5l-twinturbo-gasolina/IMG_7223.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LX',
                'year'           => 2026,
                'version'        => 'Lexus LX 600 Prestige 3.5L twinturbo gasolina',
                'engine'         => '3.5L Twin Turbo gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lx/lexus-lx-600-prestige-3-5l-twinturbo-gasolina/IMG_7210.PNG', 'vehicles/lexus/lx/lexus-lx-600-prestige-3-5l-twinturbo-gasolina/IMG_7211.PNG', 'vehicles/lexus/lx/lexus-lx-600-prestige-3-5l-twinturbo-gasolina/IMG_7212.PNG', 'vehicles/lexus/lx/lexus-lx-600-prestige-3-5l-twinturbo-gasolina/IMG_7213.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LX',
                'year'           => 2026,
                'version'        => 'Lexus LX 600 Signature 3.5L twinturbo gasolina',
                'engine'         => '3.5L Twin Turbo gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lx/lexus-lx-600-signature-3-5l-twinturbo-gasolina/IMG_7206.PNG', 'vehicles/lexus/lx/lexus-lx-600-signature-3-5l-twinturbo-gasolina/IMG_7207.PNG', 'vehicles/lexus/lx/lexus-lx-600-signature-3-5l-twinturbo-gasolina/IMG_7208.PNG', 'vehicles/lexus/lx/lexus-lx-600-signature-3-5l-twinturbo-gasolina/IMG_7209.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LX',
                'year'           => 2026,
                'version'        => 'Lexus LX 600 VIP 3.5L twinturbo gasolina',
                'engine'         => '3.5L Twin Turbo gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lx/lexus-lx-600-vip-3-5l-twinturbo-gasolina/IMG_7214.PNG', 'vehicles/lexus/lx/lexus-lx-600-vip-3-5l-twinturbo-gasolina/IMG_7215.PNG', 'vehicles/lexus/lx/lexus-lx-600-vip-3-5l-twinturbo-gasolina/IMG_7216.PNG', 'vehicles/lexus/lx/lexus-lx-600-vip-3-5l-twinturbo-gasolina/IMG_7217.PNG', 'vehicles/lexus/lx/lexus-lx-600-vip-3-5l-twinturbo-gasolina/IMG_7218.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LX',
                'year'           => 2026,
                'version'        => 'Lexus LX 700H F Sport 3.5L TwinTurbo híbrido gasolina',
                'engine'         => '3.5L Twin Turbo híbrido gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lx/lexus-lx-700h-f-sport-3-5l-twinturbo-h-brido-gasolina/IMG_7224.PNG', 'vehicles/lexus/lx/lexus-lx-700h-f-sport-3-5l-twinturbo-h-brido-gasolina/IMG_7225.PNG', 'vehicles/lexus/lx/lexus-lx-700h-f-sport-3-5l-twinturbo-h-brido-gasolina/IMG_7226.PNG', 'vehicles/lexus/lx/lexus-lx-700h-f-sport-3-5l-twinturbo-h-brido-gasolina/IMG_7227.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LX',
                'year'           => 2026,
                'version'        => 'Lexus LX 700H Signature 3.5L TwinTurbo híbrido gasolina',
                'engine'         => '3.5L Twin Turbo híbrido gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lx/lexus-lx-700h-signature-3-5l-twinturbo-h-brido-gasolina/IMG_7232.PNG', 'vehicles/lexus/lx/lexus-lx-700h-signature-3-5l-twinturbo-h-brido-gasolina/IMG_7233.PNG', 'vehicles/lexus/lx/lexus-lx-700h-signature-3-5l-twinturbo-h-brido-gasolina/IMG_7234.PNG', 'vehicles/lexus/lx/lexus-lx-700h-signature-3-5l-twinturbo-h-brido-gasolina/IMG_7235.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'LX',
                'year'           => 2026,
                'version'        => 'Lexus LX 700H VIP 3.5L TwinTurbo híbrido gasolina',
                'engine'         => '3.5L Twin Turbo híbrido gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/lx/lexus-lx-700h-vip-3-5l-twinturbo-h-brido-gasolina/IMG_7228.PNG', 'vehicles/lexus/lx/lexus-lx-700h-vip-3-5l-twinturbo-h-brido-gasolina/IMG_7229.PNG', 'vehicles/lexus/lx/lexus-lx-700h-vip-3-5l-twinturbo-h-brido-gasolina/IMG_7230.PNG', 'vehicles/lexus/lx/lexus-lx-700h-vip-3-5l-twinturbo-h-brido-gasolina/IMG_7231.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'NX',
                'year'           => 2026,
                'version'        => 'NX 350 F Sport 2.4L Turbo gasolina 4x4',
                'engine'         => '2.4L Turbo gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/nx/nx-350-f-sport-2-4l-turbo-gasolina-4x4/IMG_7240.PNG', 'vehicles/lexus/nx/nx-350-f-sport-2-4l-turbo-gasolina-4x4/IMG_7241.PNG', 'vehicles/lexus/nx/nx-350-f-sport-2-4l-turbo-gasolina-4x4/IMG_7242.PNG', 'vehicles/lexus/nx/nx-350-f-sport-2-4l-turbo-gasolina-4x4/IMG_7243.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'NX',
                'year'           => 2026,
                'version'        => 'NX 350H Premier 2.5L híbrido gasolina',
                'engine'         => '2.5L híbrido gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/nx/nx-350h-premier-2-5l-h-brido-gasolina/IMG_7236.PNG', 'vehicles/lexus/nx/nx-350h-premier-2-5l-h-brido-gasolina/IMG_7237.PNG', 'vehicles/lexus/nx/nx-350h-premier-2-5l-h-brido-gasolina/IMG_7238.PNG', 'vehicles/lexus/nx/nx-350h-premier-2-5l-h-brido-gasolina/IMG_7239.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'RX',
                'year'           => 2026,
                'version'        => 'RX 350H F Sport 2.5L híbrido gasolina 4x4',
                'engine'         => '2.5L híbrido gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/rx/rx-350h-f-sport-2-5l-h-brido-gasolina-4x4/IMG_7248.PNG', 'vehicles/lexus/rx/rx-350h-f-sport-2-5l-h-brido-gasolina-4x4/IMG_7249.PNG', 'vehicles/lexus/rx/rx-350h-f-sport-2-5l-h-brido-gasolina-4x4/IMG_7250.PNG', 'vehicles/lexus/rx/rx-350h-f-sport-2-5l-h-brido-gasolina-4x4/IMG_7251.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'RX',
                'year'           => 2026,
                'version'        => 'RX 350H Premier 2.5L híbrido gasolina 4x4',
                'engine'         => '2.5L híbrido gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/rx/rx-350h-premier-2-5l-h-brido-gasolina-4x4/IMG_7252.PNG', 'vehicles/lexus/rx/rx-350h-premier-2-5l-h-brido-gasolina-4x4/IMG_7253.PNG', 'vehicles/lexus/rx/rx-350h-premier-2-5l-h-brido-gasolina-4x4/IMG_7254.PNG', 'vehicles/lexus/rx/rx-350h-premier-2-5l-h-brido-gasolina-4x4/IMG_7255.PNG'],
            ],
            [
                'brand'          => 'lexus',
                'model'          => 'RX',
                'year'           => 2026,
                'version'        => 'RX 500H F Sport 2.4L Turbo híbrido gasolina 4x4',
                'engine'         => '2.4L Turbo híbrido gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/lexus/rx/rx-500h-f-sport-2-4l-turbo-h-brido-gasolina-4x4/IMG_7244.PNG', 'vehicles/lexus/rx/rx-500h-f-sport-2-4l-turbo-h-brido-gasolina-4x4/IMG_7245.PNG', 'vehicles/lexus/rx/rx-500h-f-sport-2-4l-turbo-h-brido-gasolina-4x4/IMG_7246.PNG', 'vehicles/lexus/rx/rx-500h-f-sport-2-4l-turbo-h-brido-gasolina-4x4/IMG_7247.PNG'],
            ],
            [
                'brand'          => 'nissan',
                'model'          => 'Navara',
                'year'           => 2026,
                'version'        => 'Navara LE Plus 2.5L 4x4 gasolina MT',
                'engine'         => '2.5L',
                'transmission'   => 'Manual',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/nissan/navara/navara-le-plus-2-5l-4x4-gasolina-mt/IMG_7256.PNG', 'vehicles/nissan/navara/navara-le-plus-2-5l-4x4-gasolina-mt/IMG_7257.PNG', 'vehicles/nissan/navara/navara-le-plus-2-5l-4x4-gasolina-mt/IMG_7258.PNG', 'vehicles/nissan/navara/navara-le-plus-2-5l-4x4-gasolina-mt/IMG_7259.PNG'],
            ],
            [
                'brand'          => 'nissan',
                'model'          => 'Navara',
                'year'           => 2026,
                'version'        => 'Navara PRO 4X 2.5L 4x4 gasolina AT',
                'engine'         => '2.5L',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/nissan/navara/navara-pro-4x-2-5l-4x4-gasolina-at/IMG_7260.PNG', 'vehicles/nissan/navara/navara-pro-4x-2-5l-4x4-gasolina-at/IMG_7261.PNG', 'vehicles/nissan/navara/navara-pro-4x-2-5l-4x4-gasolina-at/IMG_7262.PNG', 'vehicles/nissan/navara/navara-pro-4x-2-5l-4x4-gasolina-at/IMG_7264.PNG'],
            ],
            [
                'brand'          => 'nissan',
                'model'          => 'Patrol',
                'year'           => 2026,
                'version'        => 'Patrol LE Platinum City 3.5L V6 TwinTurbo Gasolina 4x4',
                'engine'         => '3.5L V6 Twin Turbo Gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/nissan/patrol/patrol-le-platinum-city-3-5l-v6-twinturbo-gasolina-4x4/IMG_7286.PNG', 'vehicles/nissan/patrol/patrol-le-platinum-city-3-5l-v6-twinturbo-gasolina-4x4/IMG_7287.PNG', 'vehicles/nissan/patrol/patrol-le-platinum-city-3-5l-v6-twinturbo-gasolina-4x4/IMG_7288.PNG', 'vehicles/nissan/patrol/patrol-le-platinum-city-3-5l-v6-twinturbo-gasolina-4x4/IMG_7289.PNG'],
            ],
            [
                'brand'          => 'nissan',
                'model'          => 'Patrol',
                'year'           => 2026,
                'version'        => 'Patrol Nismo 3.5L V6 TwinTurbo Gasolina 4x4',
                'engine'         => '3.5L V6 Twin Turbo Gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/nissan/patrol/patrol-nismo-3-5l-v6-twinturbo-gasolina-4x4/IMG_7282.PNG', 'vehicles/nissan/patrol/patrol-nismo-3-5l-v6-twinturbo-gasolina-4x4/IMG_7283.PNG', 'vehicles/nissan/patrol/patrol-nismo-3-5l-v6-twinturbo-gasolina-4x4/IMG_7284.PNG', 'vehicles/nissan/patrol/patrol-nismo-3-5l-v6-twinturbo-gasolina-4x4/IMG_7285.PNG'],
            ],
            [
                'brand'          => 'nissan',
                'model'          => 'Patrol',
                'year'           => 2026,
                'version'        => 'Patrol SE Platinum City 3.8L V6 Gasolina 4x4',
                'engine'         => '3.8L V6 Gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/nissan/patrol/patrol-se-platinum-city-3-8l-v6-gasolina-4x4/IMG_7276.PNG', 'vehicles/nissan/patrol/patrol-se-platinum-city-3-8l-v6-gasolina-4x4/IMG_7277.PNG', 'vehicles/nissan/patrol/patrol-se-platinum-city-3-8l-v6-gasolina-4x4/IMG_7278.PNG', 'vehicles/nissan/patrol/patrol-se-platinum-city-3-8l-v6-gasolina-4x4/IMG_7279.PNG'],
            ],
            [
                'brand'          => 'nissan',
                'model'          => 'Patrol',
                'year'           => 2026,
                'version'        => 'Patrol XE 3.8L V6 Gasolina 4x4',
                'engine'         => '3.8L V6 Gasolina',
                'transmission'   => 'Automática',
                'origin_country' => 'Emiratos Árabes Unidos',
                'availability'   => 'on_request',
                'images'         => ['vehicles/nissan/patrol/patrol-xe-3-8l-v6-gasolina-4x4/IMG_7272.PNG', 'vehicles/nissan/patrol/patrol-xe-3-8l-v6-gasolina-4x4/IMG_7273.PNG', 'vehicles/nissan/patrol/patrol-xe-3-8l-v6-gasolina-4x4/IMG_7274.PNG', 'vehicles/nissan/patrol/patrol-xe-3-8l-v6-gasolina-4x4/IMG_7275.PNG'],
            ],
        ];

        foreach ($vehicles as $data) {
            $brand = Brand::where('slug', $data['brand'])->first();
            if (!$brand) continue;

            // Lógica de estatus: highlander inactivo, lexus solo lx activo
            $estatus = 'activo';
            $firstImage = $data['images'][0] ?? '';
            $isHighlander = $data['brand'] === 'toyota' && $data['model'] === 'Highlander';
            $isHighlanderByPath = str_starts_with($firstImage, 'vehicles/toyota/highlander/');
            $isLexusNoLx = $data['brand'] === 'lexus' && $data['model'] !== 'LX';
            if ($isHighlander || $isHighlanderByPath || $isLexusNoLx) {
                $estatus = 'inactivo';
            }
            // Permitir override explícito si se añade 'estatus' en el array
            if (isset($data['estatus'])) {
                $estatus = $data['estatus'];
            }

            Vehicle::updateOrCreate(
                ['brand_id' => $brand->id, 'model' => $data['model'], 'version' => $data['version']],
                [
                    'year'           => $data['year'],
                    'engine'         => $data['engine'],
                    'transmission'   => $data['transmission'],
                    'origin_country' => $data['origin_country'],
                    'availability'   => $data['availability'],
                    'images'         => $data['images'],
                    'estatus'        => $estatus,
                    'active'         => $estatus === 'activo',
                ]
            );
        }

        // Normalización final: asegurar reglas incluso si se añade nueva versión sin marcar
        $toyotaId = Brand::where('slug', 'toyota')->value('id');
        $lexusId = Brand::where('slug', 'lexus')->value('id');
        if ($toyotaId) {
            Vehicle::where('brand_id', $toyotaId)->where('model', 'Highlander')->update(['estatus' => 'inactivo', 'active' => false]);
            Vehicle::where('brand_id', $toyotaId)->where('images', 'like', '%vehicles/toyota/highlander/%')->update(['estatus' => 'inactivo', 'active' => false]);
        }
        if ($lexusId) {
            Vehicle::where('brand_id', $lexusId)->where('model', '!=', 'LX')->update(['estatus' => 'inactivo', 'active' => false]);
            Vehicle::where('brand_id', $lexusId)->where('model', 'LX')->update(['estatus' => 'activo', 'active' => true]);
        }
    }
}

